/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Предстоящие брони всех типов событий (startsAt >= сейчас), по возрастанию startsAt. */
        get: operations["Bookings_list"];
        put?: never;
        /**
         * @description Создать бронирование (гость). Начало должно быть кратно 15 минутам,
         *     попадать в окно 14 дней и в свободный слот.
         */
        post: operations["Bookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список всех типов событий. Используется гостем и владельцем. */
        get: operations["EventTypes_list"];
        put?: never;
        /** @description Создать тип события. id (slug) задаёт владелец, дубликат → 409. */
        post: operations["EventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{eventTypeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить тип события по id. */
        get: operations["EventTypes_get"];
        /** @description Обновить тип события. Поле id в теле игнорируется. */
        put: operations["EventTypes_update"];
        post?: never;
        /**
         * @description Удалить тип события. Существующие брони этого типа сохраняются,
         *     новые — создать нельзя (404).
         */
        delete: operations["EventTypes_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{eventTypeId}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Свободные слоты типа события на окно записи (14 дней).
         *     Слот предлагается, если событие целиком помещается в рабочие часы дня
         *     и не пересекается с существующими бронями.
         */
        get: operations["EventTypes_listSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Текущее расписание владельца по умолчанию. */
        get: operations["Schedule_get"];
        /** @description Полностью заменить расписание владельца по умолчанию. */
        put: operations["Schedule_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BadRequestError: {
            /** @enum {string} */
            code: "VALIDATION_ERROR" | "CONTACT_REQUIRED" | "SLOT_MISALIGNED" | "SLOT_OUT_OF_WINDOW" | "SLOT_OUTSIDE_SCHEDULE";
            message: string;
        };
        /** @description Бронирование. */
        Booking: {
            /** Format: uuid */
            id: string;
            eventType: components["schemas"]["BookingEventType"];
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            guestName: string;
            guestPhone?: string;
            guestEmail?: string;
            guestComment?: string;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Данные для создания бронирования. */
        BookingCreate: {
            /** @description id (slug) выбранного типа события. */
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Начало слота, ISO 8601 UTC. Кратно 15 минутам и внутри окна записи.
             */
            startsAt: string;
            guestName: string;
            /** @description Телефон гостя. Обязателен хотя бы один контакт: guestPhone или guestEmail. */
            guestPhone?: string;
            /**
             * Format: email
             * @description Email гостя. Обязателен хотя бы один контакт: guestPhone или guestEmail.
             */
            guestEmail?: string;
            guestComment?: string;
        };
        /** @description Снимок типа события на момент бронирования. Хранится даже после удаления типа. */
        BookingEventType: {
            id: string;
            title: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        ConflictError: {
            /** @enum {string} */
            code: "DUPLICATE_EVENT_TYPE_ID" | "SLOT_BUSY";
            message: string;
        };
        /** @description Тип события — вид брони, который публикует владелец календаря. */
        EventType: {
            /** @description Уникальный идентификатор (slug), задаётся владельцем при создании. Пример: "intro-call". */
            id: string;
            /** @description Название, отображается гостю. Пример: "Знакомственный звонок". */
            title: string;
            /** @description Описание для страницы выбора вида брони. */
            description: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах, кратна сетке слотов (15 минут).
             */
            durationMinutes: number;
            /**
             * @description Собственное расписание доступности. Если не задано — используется
             *     расписание владельца по умолчанию (GET/PUT /schedule).
             */
            availability?: components["schemas"]["WeeklySchedule"];
        };
        NotFoundError: {
            /** @enum {string} */
            code: "EVENT_TYPE_NOT_FOUND";
            message: string;
        };
        /** @description Свободный слот длиной в длительность типа события. */
        Slot: {
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
        };
        /** @description Ответ со свободными слотами на окно записи. */
        SlotsResponse: {
            /**
             * Format: date
             * @description Первый день окна записи — сегодня (UTC).
             */
            windowStartsOn: string;
            /**
             * Format: date
             * @description Последний день окна записи (14 дней, включая сегодняшний).
             */
            windowEndsOn: string;
            /** @description Свободные слоты по возрастанию startsAt. */
            slots: components["schemas"]["Slot"][];
        };
        /** @description Интервал рабочего времени внутри дня, например 09:00–13:00. */
        TimeInterval: {
            /**
             * Format: time
             * @description Начало интервала, формат HH:mm.
             */
            start: string;
            /**
             * Format: time
             * @description Конец интервала, формат HH:mm. Должен быть больше начала.
             */
            end: string;
        };
        /** @description Недельное расписание. Пустой массив интервалов — день недоступен. */
        WeeklySchedule: {
            /** @description Понедельник. */
            mon: components["schemas"]["TimeInterval"][];
            /** @description Вторник. */
            tue: components["schemas"]["TimeInterval"][];
            /** @description Среда. */
            wed: components["schemas"]["TimeInterval"][];
            /** @description Четверг. */
            thu: components["schemas"]["TimeInterval"][];
            /** @description Пятница. */
            fri: components["schemas"]["TimeInterval"][];
            /** @description Суббота. */
            sat: components["schemas"]["TimeInterval"][];
            /** @description Воскресенье. */
            sun: components["schemas"]["TimeInterval"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Bookings_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
    Bookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestError"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
        };
    };
    EventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    EventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventType"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestError"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
        };
    };
    EventTypes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    EventTypes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventType"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestError"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    EventTypes_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    EventTypes_listSlots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotsResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    Schedule_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklySchedule"];
                };
            };
        };
    };
    Schedule_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeeklySchedule"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklySchedule"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestError"];
                };
            };
        };
    };
}
